### ISSUE TITLE
Revamp common names list

### ISSUE THREAD

**Issue by Toast732** [THE-SIMPLE-MARK/SW-Anti-Reuploads-Bot#1]
Add a command which can only be used by only specific discord users "/commonname (name)", which allows them to add common names without having it hard coded.

Also, if a name of a creation gets removed from the workshop 5-10 times, automatically add it to the list of common names

**Comment by THE-SIMPLE-MARK** [comment]
Hey! Thank you for investing your time into the development of my projects!

I do not want to store common names in the database because I do not want this feature to be abused by users with bad intentions. On the other hand, I'll be adding common names with every update!

Thanks for your help and have a good day,
Mark
